// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

async function makeRequest(url) {
  var response = await fetch(url);
  var json = await response.json();
  console.log(json);
  return json;
}

function useTodoList() {
  var match = React.useState(function () {
        
      });
  var setTodoList = match[1];
  React.useEffect((function () {
          var fetchTodoList = async function () {
            var response = await makeRequest("https://jsonplaceholder.typicode.com/todos?userId=1");
            return setTodoList(function (param) {
                        return Caml_option.some(response);
                      });
          };
          fetchTodoList();
        }), []);
  return match[0];
}

export {
  makeRequest ,
  useTodoList ,
}
/* react Not a pure module */
