// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "../entities/Todo.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function TodoList(props) {
  var todoList = Todo.useTodoList();
  if (todoList !== undefined) {
    return JsxRuntime.jsx("ul", {
                children: Belt_Array.map(todoList, (function (todo) {
                        return JsxRuntime.jsxs("li", {
                                    children: [
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("input", {
                                                    className: "mr-2",
                                                    checked: todo.completed,
                                                    type: "checkbox"
                                                  }),
                                              JsxRuntime.jsx("span", {
                                                    children: todo.title,
                                                    className: "text-gray-800"
                                                  })
                                            ],
                                            className: "flex items-center"
                                          }),
                                      JsxRuntime.jsx("button", {
                                            children: "Delete",
                                            className: "text-red-500 focus:outline-none hover:bg-red-200 rounded-full px-3 py-1"
                                          })
                                    ],
                                    className: "flex items-center justify-between py-2"
                                  });
                      })),
                className: "divide-y divide-gray-300 max-h-80 overflow-auto"
              });
  } else {
    return null;
  }
}

var make = TodoList;

export {
  make ,
}
/* Todo Not a pure module */
