// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

var sampleData = [
  {
    userId: 1,
    id: 1,
    title: "delectus aut autem",
    completed: false
  },
  {
    userId: 1,
    id: 2,
    title: "quis ut nam facilis et officia qui",
    completed: false
  },
  {
    userId: 1,
    id: 3,
    title: "fugiat veniam minus",
    completed: false
  },
  {
    userId: 1,
    id: 4,
    title: "et porro tempora",
    completed: true
  }
];

function TodoList(props) {
  return JsxRuntime.jsx("ul", {
              children: Belt_Array.map(sampleData, (function (todo) {
                      return JsxRuntime.jsxs("li", {
                                  children: [
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("input", {
                                                  className: "mr-2",
                                                  checked: todo.completed,
                                                  type: "checkbox"
                                                }),
                                            JsxRuntime.jsx("span", {
                                                  children: todo.title,
                                                  className: "text-gray-800"
                                                })
                                          ],
                                          className: "flex items-center"
                                        }),
                                    JsxRuntime.jsx("button", {
                                          children: "Delete",
                                          className: "text-red-500 focus:outline-none hover:bg-red-200 rounded-full px-3 py-1"
                                        })
                                  ],
                                  className: "flex items-center justify-between py-2"
                                }, String(todo.id));
                    })),
              className: "divide-y divide-gray-300"
            });
}

var make = TodoList;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
